spring:
  application:
    name: sistema-energia

  datasource:
    url: jdbc:postgresql://localhost:5432/sistema_energia
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1996

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: always

h2:
  console:
    enabled: false

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
